; generated by PrusaSlicer 2.6.1+linux-x64-GTK3 on 2023-10-01 at 13:39:35 UTC
; manually modified to change the print order outside to inside.

; 

; external perimeters extrusion width = 0.42mm
; perimeters extrusion width = 0.44mm
; infill extrusion width = 0.44mm
; solid infill extrusion width = 0.44mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.42mm

; external perimeters extrusion width = 0.42mm
; perimeters extrusion width = 0.44mm
; infill extrusion width = 0.44mm
; solid infill extrusion width = 0.44mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.42mm

; external perimeters extrusion width = 0.42mm
; perimeters extrusion width = 0.44mm
; infill extrusion width = 0.44mm
; solid infill extrusion width = 0.44mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.42mm

; external perimeters extrusion width = 0.42mm
; perimeters extrusion width = 0.44mm
; infill extrusion width = 0.44mm
; solid infill extrusion width = 0.44mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.42mm

; external perimeters extrusion width = 0.42mm
; perimeters extrusion width = 0.44mm
; infill extrusion width = 0.44mm
; solid infill extrusion width = 0.44mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.42mm

; external perimeters extrusion width = 0.42mm
; perimeters extrusion width = 0.44mm
; infill extrusion width = 0.44mm
; solid infill extrusion width = 0.44mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.42mm

; external perimeters extrusion width = 0.42mm
; perimeters extrusion width = 0.44mm
; infill extrusion width = 0.44mm
; solid infill extrusion width = 0.44mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.42mm

; external perimeters extrusion width = 0.42mm
; perimeters extrusion width = 0.44mm
; infill extrusion width = 0.44mm
; solid infill extrusion width = 0.44mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.42mm

; external perimeters extrusion width = 0.42mm
; perimeters extrusion width = 0.44mm
; infill extrusion width = 0.44mm
; solid infill extrusion width = 0.44mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.42mm

; external perimeters extrusion width = 0.42mm
; perimeters extrusion width = 0.44mm
; infill extrusion width = 0.44mm
; solid infill extrusion width = 0.44mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.42mm

; external perimeters extrusion width = 0.42mm
; perimeters extrusion width = 0.44mm
; infill extrusion width = 0.44mm
; solid infill extrusion width = 0.44mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.42mm

M201 X500 Y500 Z100 E5000 ; sets maximum accelerations, mm/sec^2
M203 X500 Y500 Z10 E60 ; sets maximum feedrates, mm / sec
M204 S500 T1000 ; sets acceleration (S) and retract acceleration (R), mm/sec^2
M205 X8.00 Y8.00 Z0.40 E5.00 ; sets the jerk limits, mm/sec
M205 S0 T0 ; sets the minimum extruding and travel feed rate, mm/sec
;TYPE:Custom
G90 ; use absolute coordinates
M83 ; extruder relative mode
M104 S150 ; set temporary nozzle temp to prevent oozing during homing
M140 S60 ; set final bed temp
G4 S30 ; allow partial nozzle warmup
G28 ; home all axis
G1 Z50 F240
G1 X2.0 Y10 F3000
M104 S225 ; set final nozzle temp
M190 S60 ; wait for bed temp to stabilize
M109 S225 ; wait for nozzle temp to stabilize
G1 Z0.28 F240
G92 E0
G1 X2.0 Y140 E10 F1500 ; prime the nozzle
G1 X2.3 Y140 F5000
G92 E0
G1 X2.3 Y10 E10 F1200 ; prime the nozzle
G92 E0
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
; Filament gcode
M107
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0
;0.2


G1 E-3 F3600
G1 Z.2 F9000
;AFTER_LAYER_CHANGE
;0.2
G1 X6.822 Y1.698
G1 E3 F2400
M204 S500
;TYPE:Skirt/Brim
;WIDTH:0.42
G1 F1200
G1 X7.017 Y.917 E.02524
G1 X8.107 Y-.297 E.05116
G1 X10 Y-.877 E.06208
G1 X290 Y-.877 E8.7792
G1 X291.583 Y-.483 E.05115
G1 X292.797 Y.607 E.05116
G1 X293.377 Y2.5 E.06208
G1 X293.377 Y282.5 E8.7792
G1 X292.983 Y284.083 E.05115
G1 X291.893 Y285.297 E.05116
G1 X290 Y285.877 E.06208
G1 X10 Y285.877 E8.7792
G1 X8.417 Y285.483 E.05115
G1 X7.203 Y284.393 E.05116
G1 X6.623 Y282.5 E.06208
G1 X6.623 Y2.5 E8.7792
G1 X6.808 Y1.756 E.02404

; printing object BedLevelTest.stl_1 id:0 copy 0
G1 E-2.1 F3600
;WIPE_START
G1 F7200
G1 X47.215 Y37.712 E-.9
;WIPE_END
G1 X10.379 Y2.7 F9000
G1 E3 F2400
;WIDTH:0.4
G1 F1200
G1 X289.621 Y2.7 E8.29106
;WIDTH:0.430633
G1 X289.695 Y2.715 E.00243
;WIDTH:0.461266
G1 X289.769 Y2.731 E.00263
G1 X289.785 Y2.805 E.00263
;WIDTH:0.430633
G1 X289.8 Y2.879 E.00243
;WIDTH:0.4
G1 X289.8 Y282.121 E8.29106
;WIDTH:0.430633
G1 X289.785 Y282.195 E.00243
;WIDTH:0.461266
G1 X289.769 Y282.269 E.00263
G1 X289.695 Y282.285 E.00263
;WIDTH:0.430633
G1 X289.621 Y282.3 E.00243
;WIDTH:0.4
G1 X10.379 Y282.3 E8.29106
;WIDTH:0.430632
G1 X10.305 Y282.285 E.00243
;WIDTH:0.461264
G1 X10.231 Y282.269 E.00263
G1 X10.215 Y282.195 E.00263
;WIDTH:0.430632
G1 X10.2 Y282.121 E.00243
;WIDTH:0.4
G1 X10.2 Y2.879 E8.29106
;WIDTH:0.430632
G1 X10.215 Y2.805 E.00243
;WIDTH:0.461264
G1 X10.231 Y2.731 E.00263
G1 X10.305 Y2.715 E.00263
;WIDTH:0.430632
G1 X10.32 Y2.712 E.00049
; stop printing object BedLevelTest.stl_1 id:0 copy 0

; printing object BedLevelTest.stl_2 id:1 copy 0
G1 E-2.1 F3600
;WIPE_START
G1 F7200
G1 X37.215 Y27.712 E-.9
;WIPE_END
G1 X15.379 Y7.7 F9000
G1 E3 F2400
;WIDTH:0.4
G1 F1200
G1 X284.621 Y7.7 E7.99415
;WIDTH:0.430633
G1 X284.695 Y7.715 E.00243
;WIDTH:0.461266
G1 X284.769 Y7.731 E.00263
G1 X284.785 Y7.805 E.00263
;WIDTH:0.430633
G1 X284.8 Y7.879 E.00243
;WIDTH:0.4
G1 X284.8 Y277.121 E7.99415
;WIDTH:0.430633
G1 X284.785 Y277.195 E.00243
;WIDTH:0.461266
G1 X284.769 Y277.269 E.00263
G1 X284.695 Y277.285 E.00263
;WIDTH:0.430633
G1 X284.621 Y277.3 E.00243
;WIDTH:0.4
G1 X15.379 Y277.3 E7.99415
;WIDTH:0.430632
G1 X15.305 Y277.285 E.00243
;WIDTH:0.461264
G1 X15.231 Y277.269 E.00263
G1 X15.215 Y277.195 E.00263
;WIDTH:0.430632
G1 X15.2 Y277.121 E.00243
;WIDTH:0.4
G1 X15.2 Y7.879 E7.99415
;WIDTH:0.430632
G1 X15.215 Y7.805 E.00243
;WIDTH:0.461264
G1 X15.231 Y7.731 E.00263
G1 X15.305 Y7.715 E.00263
;WIDTH:0.430632
G1 X15.32 Y7.712 E.00049
; stop printing object BedLevelTest.stl_2 id:1 copy 0

; printing object BedLevelTest.stl_3 id:2 copy 0
G1 E-2.1 F3600
;WIPE_START
G1 F7200
G1 X57.215 Y47.712 E-.9
;WIPE_END
G1 X20.379 Y12.7 F9000
G1 E3 F2400
;WIDTH:0.399992
G1 F1200
G1 X279.621 Y12.7 E7.69706
;WIDTH:0.430624
G1 X279.695 Y12.715 E.00243
;WIDTH:0.461256
G1 X279.769 Y12.731 E.00263
G1 X279.785 Y12.805 E.00263
;WIDTH:0.430624
G1 X279.8 Y12.879 E.00243
;WIDTH:0.399992
G1 X279.8 Y272.121 E7.69706
;WIDTH:0.430624
G1 X279.785 Y272.195 E.00243
;WIDTH:0.461256
G1 X279.769 Y272.269 E.00263
G1 X279.695 Y272.285 E.00263
;WIDTH:0.430624
G1 X279.621 Y272.3 E.00243
;WIDTH:0.399992
G1 X20.379 Y272.3 E7.69706
;WIDTH:0.430623
G1 X20.305 Y272.285 E.00243
;WIDTH:0.461254
G1 X20.231 Y272.269 E.00263
G1 X20.215 Y272.195 E.00263
;WIDTH:0.430623
G1 X20.2 Y272.121 E.00243
;WIDTH:0.399992
G1 X20.2 Y12.879 E7.69706
;WIDTH:0.430623
G1 X20.215 Y12.805 E.00243
;WIDTH:0.461254
G1 X20.231 Y12.731 E.00263
G1 X20.305 Y12.715 E.00263
;WIDTH:0.430623
G1 X20.32 Y12.712 E.00049
; stop printing object BedLevelTest.stl_3 id:2 copy 0

; printing object BedLevelTest.stl_4 id:3 copy 0
G1 E-2.1 F3600
;WIPE_START
G1 F7200
G1 X62.215 Y52.712 E-.9
;WIPE_END
G1 X25.379 Y17.7 F9000
G1 E3 F2400
;WIDTH:0.4
G1 F1200
G1 X274.621 Y17.7 E7.40033
;WIDTH:0.430633
G1 X274.695 Y17.715 E.00243
;WIDTH:0.461266
G1 X274.769 Y17.731 E.00263
G1 X274.785 Y17.805 E.00263
;WIDTH:0.430633
G1 X274.8 Y17.879 E.00243
;WIDTH:0.4
G1 X274.8 Y267.121 E7.40033
;WIDTH:0.430633
G1 X274.785 Y267.195 E.00243
;WIDTH:0.461266
G1 X274.769 Y267.269 E.00263
G1 X274.695 Y267.285 E.00263
;WIDTH:0.430633
G1 X274.621 Y267.3 E.00243
;WIDTH:0.4
G1 X25.379 Y267.3 E7.40033
;WIDTH:0.430632
G1 X25.305 Y267.285 E.00243
;WIDTH:0.461264
G1 X25.231 Y267.269 E.00263
G1 X25.215 Y267.195 E.00263
;WIDTH:0.430632
G1 X25.2 Y267.121 E.00243
;WIDTH:0.4
G1 X25.2 Y17.879 E7.40033
;WIDTH:0.430632
G1 X25.215 Y17.805 E.00243
;WIDTH:0.461264
G1 X25.231 Y17.731 E.00263
G1 X25.305 Y17.715 E.00263
;WIDTH:0.430632
G1 X25.32 Y17.712 E.00049
; stop printing object BedLevelTest.stl_4 id:3 copy 0

; printing object BedLevelTest.stl_5 id:4 copy 0
G1 E-2.1 F3600
;WIPE_START
G1 F7200
G1 X22.215 Y12.712 E-.9
;WIPE_END
G1 X30.379 Y22.7 F9000
G1 E3 F2400
;WIDTH:0.4
G1 F1200
G1 X269.621 Y22.7 E7.10341
;WIDTH:0.430633
G1 X269.695 Y22.715 E.00243
;WIDTH:0.461266
G1 X269.769 Y22.731 E.00263
G1 X269.785 Y22.805 E.00263
;WIDTH:0.430633
G1 X269.8 Y22.879 E.00243
;WIDTH:0.4
G1 X269.8 Y262.121 E7.10341
;WIDTH:0.430633
G1 X269.785 Y262.195 E.00243
;WIDTH:0.461266
G1 X269.769 Y262.269 E.00263
G1 X269.695 Y262.285 E.00263
;WIDTH:0.430633
G1 X269.621 Y262.3 E.00243
;WIDTH:0.4
G1 X30.379 Y262.3 E7.10341
;WIDTH:0.430632
G1 X30.305 Y262.285 E.00243
;WIDTH:0.461264
G1 X30.231 Y262.269 E.00263
G1 X30.215 Y262.195 E.00263
;WIDTH:0.430632
G1 X30.2 Y262.121 E.00243
;WIDTH:0.4
G1 X30.2 Y22.879 E7.10341
;WIDTH:0.430632
G1 X30.215 Y22.805 E.00243
;WIDTH:0.461264
G1 X30.231 Y22.731 E.00263
G1 X30.305 Y22.715 E.00263
;WIDTH:0.430632
G1 X30.32 Y22.712 E.00049
; stop printing object BedLevelTest.stl_5 id:4 copy 0

; printing object BedLevelTest.stl_6 id:5 copy 0
G1 E-2.1 F3600
;WIPE_START
G1 F7200
G1 X42.215 Y32.712 E-.9
;WIPE_END
G1 X35.379 Y27.7 F9000
G1 E3 F2400
;WIDTH:0.4
G1 F1200
G1 X264.621 Y27.7 E6.8065
;WIDTH:0.430633
G1 X264.695 Y27.715 E.00243
;WIDTH:0.461266
G1 X264.769 Y27.731 E.00263
G1 X264.785 Y27.805 E.00263
;WIDTH:0.430633
G1 X264.8 Y27.879 E.00243
;WIDTH:0.4
G1 X264.8 Y257.121 E6.8065
;WIDTH:0.430633
G1 X264.785 Y257.195 E.00243
;WIDTH:0.461266
G1 X264.769 Y257.269 E.00263
G1 X264.695 Y257.285 E.00263
;WIDTH:0.430633
G1 X264.621 Y257.3 E.00243
;WIDTH:0.4
G1 X35.379 Y257.3 E6.8065
;WIDTH:0.430632
G1 X35.305 Y257.285 E.00243
;WIDTH:0.461264
G1 X35.231 Y257.269 E.00263
G1 X35.215 Y257.195 E.00263
;WIDTH:0.430632
G1 X35.2 Y257.121 E.00243
;WIDTH:0.4
G1 X35.2 Y27.879 E6.8065
;WIDTH:0.430632
G1 X35.215 Y27.805 E.00243
;WIDTH:0.461264
G1 X35.231 Y27.731 E.00263
G1 X35.305 Y27.715 E.00263
;WIDTH:0.430632
G1 X35.32 Y27.712 E.00049
; stop printing object BedLevelTest.stl_6 id:5 copy 0

; printing object BedLevelTest.stl_7 id:6 copy 0
G1 E-2.1 F3600
;WIPE_START
G1 F7200
G1 X7.017 Y.917 E-.4107
G1 X7.705 Y.151 E-.4893
;WIPE_END
G1 X40.379 Y32.7 F9000
G1 E3 F2400
;TYPE:External perimeter
;WIDTH:0.4
G1 F1200
G1 X259.621 Y32.7 E6.50959
;WIDTH:0.430633
G1 X259.695 Y32.715 E.00243
;WIDTH:0.461266
G1 X259.769 Y32.731 E.00263
G1 X259.785 Y32.805 E.00263
;WIDTH:0.430633
G1 X259.8 Y32.879 E.00243
;WIDTH:0.4
G1 X259.8 Y252.121 E6.50959
;WIDTH:0.430633
G1 X259.785 Y252.195 E.00243
;WIDTH:0.461266
G1 X259.769 Y252.269 E.00263
G1 X259.695 Y252.285 E.00263
;WIDTH:0.430633
G1 X259.621 Y252.3 E.00243
;WIDTH:0.4
G1 X40.379 Y252.3 E6.50959
;WIDTH:0.430632
G1 X40.305 Y252.285 E.00243
;WIDTH:0.461264
G1 X40.231 Y252.269 E.00263
G1 X40.215 Y252.195 E.00263
;WIDTH:0.430632
G1 X40.2 Y252.121 E.00243
;WIDTH:0.4
G1 X40.2 Y32.879 E6.50959
;WIDTH:0.430632
G1 X40.215 Y32.805 E.00243
;WIDTH:0.461264
G1 X40.231 Y32.731 E.00263
G1 X40.305 Y32.715 E.00263
;WIDTH:0.430632
G1 X40.32 Y32.712 E.00049
; stop printing object BedLevelTest.stl_7 id:6 copy 0

; printing object BedLevelTest.stl_8 id:7 copy 0
G1 E-2.1 F3600
;WIPE_START
G1 F7200
G1 X27.215 Y17.712 E-.9
;WIPE_END
G1 X45.379 Y37.7 F9000
G1 E3 F2400
;WIDTH:0.4
G1 F1200
G1 X254.621 Y37.7 E6.21267
;WIDTH:0.430633
G1 X254.695 Y37.715 E.00243
;WIDTH:0.461266
G1 X254.769 Y37.731 E.00263
G1 X254.785 Y37.805 E.00263
;WIDTH:0.430633
G1 X254.8 Y37.879 E.00243
;WIDTH:0.4
G1 X254.8 Y247.121 E6.21267
;WIDTH:0.430633
G1 X254.785 Y247.195 E.00243
;WIDTH:0.461266
G1 X254.769 Y247.269 E.00263
G1 X254.695 Y247.285 E.00263
;WIDTH:0.430633
G1 X254.621 Y247.3 E.00243
;WIDTH:0.4
G1 X45.379 Y247.3 E6.21267
;WIDTH:0.430632
G1 X45.305 Y247.285 E.00243
;WIDTH:0.461264
G1 X45.231 Y247.269 E.00263
G1 X45.215 Y247.195 E.00263
;WIDTH:0.430632
G1 X45.2 Y247.121 E.00243
;WIDTH:0.4
G1 X45.2 Y37.879 E6.21267
;WIDTH:0.430632
G1 X45.215 Y37.805 E.00243
;WIDTH:0.461264
G1 X45.231 Y37.731 E.00263
G1 X45.305 Y37.715 E.00263
;WIDTH:0.430632
G1 X45.32 Y37.712 E.00049
; stop printing object BedLevelTest.stl_8 id:7 copy 0

; printing object BedLevelTest.stl_9 id:8 copy 0
G1 E-2.1 F3600
;WIPE_START
G1 F7200
G1 X32.215 Y22.712 E-.9
;WIPE_END
G1 X50.379 Y42.7 F9000
G1 E3 F2400
;WIDTH:0.4
G1 F1200
G1 X249.621 Y42.7 E5.91576
;WIDTH:0.430633
G1 X249.695 Y42.715 E.00243
;WIDTH:0.461266
G1 X249.769 Y42.731 E.00263
G1 X249.785 Y42.805 E.00263
;WIDTH:0.430633
G1 X249.8 Y42.879 E.00243
;WIDTH:0.4
G1 X249.8 Y242.121 E5.91576
;WIDTH:0.430633
G1 X249.785 Y242.195 E.00243
;WIDTH:0.461266
G1 X249.769 Y242.269 E.00263
G1 X249.695 Y242.285 E.00263
;WIDTH:0.430633
G1 X249.621 Y242.3 E.00243
;WIDTH:0.4
G1 X50.379 Y242.3 E5.91576
;WIDTH:0.430632
G1 X50.305 Y242.285 E.00243
;WIDTH:0.461264
G1 X50.231 Y242.269 E.00263
G1 X50.215 Y242.195 E.00263
;WIDTH:0.430632
G1 X50.2 Y242.121 E.00243
;WIDTH:0.4
G1 X50.2 Y42.879 E5.91576
;WIDTH:0.430632
G1 X50.215 Y42.805 E.00243
;WIDTH:0.461264
G1 X50.231 Y42.731 E.00263
G1 X50.305 Y42.715 E.00263
;WIDTH:0.430632
G1 X50.32 Y42.712 E.00049
; stop printing object BedLevelTest.stl_9 id:8 copy 0

; printing object BedLevelTest.stl_10 id:9 copy 0
G1 E-2.1 F3600
;WIPE_START
G1 F7200
G1 X12.215 Y2.712 E-.9
;WIPE_END
G1 X55.379 Y47.7 F9000
G1 E3 F2400
;WIDTH:0.4
G1 F1200
G1 X244.621 Y47.7 E5.61885
;WIDTH:0.430633
G1 X244.695 Y47.715 E.00243
;WIDTH:0.461266
G1 X244.769 Y47.731 E.00263
G1 X244.785 Y47.805 E.00263
;WIDTH:0.430633
G1 X244.8 Y47.879 E.00243
;WIDTH:0.4
G1 X244.8 Y237.121 E5.61885
;WIDTH:0.430633
G1 X244.785 Y237.195 E.00243
;WIDTH:0.461266
G1 X244.769 Y237.269 E.00263
G1 X244.695 Y237.285 E.00263
;WIDTH:0.430633
G1 X244.621 Y237.3 E.00243
;WIDTH:0.4
G1 X55.379 Y237.3 E5.61885
;WIDTH:0.430632
G1 X55.305 Y237.285 E.00243
;WIDTH:0.461264
G1 X55.231 Y237.269 E.00263
G1 X55.215 Y237.195 E.00263
;WIDTH:0.430632
G1 X55.2 Y237.121 E.00243
;WIDTH:0.4
G1 X55.2 Y47.879 E5.61885
;WIDTH:0.430632
G1 X55.215 Y47.805 E.00243
;WIDTH:0.461264
G1 X55.231 Y47.731 E.00263
G1 X55.305 Y47.715 E.00263
;WIDTH:0.430632
G1 X55.32 Y47.712 E.00049
; stop printing object BedLevelTest.stl_10 id:9 copy 0

G1 E-2.1 F3600
;WIPE_START
G1 F7200;_WIPE
G1 X52.215 Y42.712 E-.9
;WIPE_END
M107
;TYPE:Custom
; Filament-specific end gcode 
;END gcode for filament
G1 Z2.2 F600 ; Move print head up
G1 X5 Y246.5 F9000 ; present print
G1 Z70.2 F600 ; Move print head further up
G1 Z204 F600 ; Move print head further up
M140 S0 ; turn off heatbed
M104 S0 ; turn off temperature
M107 ; turn off fan
M84 X Y E ; disable motors

; prusaslicer_config = begin
; autoemit_temperature_commands = 1
; avoid_crossing_curled_overhangs = 0
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 0x-5,300x-5,300x290,0x290
; bed_temperature = 60
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\nG92 E0\n;{layer_z}\n\n
; between_objects_gcode = 
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 4
; bottom_solid_min_thickness = 0
; bridge_acceleration = 250
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 0.95
; bridge_speed = 25
; brim_separation = 0
; brim_type = outer_only
; brim_width = 0
; color_change_gcode = M600
; compatible_printers_condition_cummulative = "printer_model=~/(ENDER|CR|SERMOON).*/ and nozzle_diameter[0]==0.4";printer_notes=~/.*PRINTER_VENDOR_CREALITY.*/
; complete_objects = 0
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 500
; default_filament_profile = "Generic PLA @CREALITY"
; default_print_profile = "0.16 mm OPTIMAL (0.4 mm nozzle) @CREALITY"
; deretract_speed = 40
; disable_fan_first_layers = 1
; dont_support_bridges = 1
; draft_shield = disabled
; duplicate_distance = 6
; elefant_foot_compensation = 0.1
; enable_dynamic_fan_speeds = 0
; enable_dynamic_overhang_speeds = 0
; end_filament_gcode = "; Filament-specific end gcode \n;END gcode for filament\n"
; end_gcode = {if max_layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+2, max_print_height)} F600 ; Move print head up{endif}\nG1 X5 Y{print_bed_max[1]*0.85} F{travel_speed*60} ; present print\n{if max_layer_z < max_print_height-10}G1 Z{z_offset+min(max_layer_z+70, max_print_height-10)} F600 ; Move print head further up{endif}\n{if max_layer_z < max_print_height*0.6}G1 Z{max_print_height*0.6} F600 ; Move print head further up{endif}\nM140 S0 ; turn off heatbed\nM104 S0 ; turn off temperature\nM107 ; turn off fan\nM84 X Y E ; disable motors
; external_perimeter_acceleration = 0
; external_perimeter_extrusion_width = 0.42
; external_perimeter_speed = 30
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 0
; extra_perimeters_on_overhangs = 0
; extruder_clearance_height = 25
; extruder_clearance_radius = 55
; extruder_colour = #FCE94F
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 0.44
; fan_always_on = 1
; fan_below_layer_time = 100
; filament_colour = #FFFFFF
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 20
; filament_density = 1.24
; filament_diameter = 1.75
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 15
; filament_minimal_purge_on_wipe_tower = 15
; filament_multitool_ramming = 0
; filament_multitool_ramming_flow = 10
; filament_multitool_ramming_volume = 10
; filament_notes = ""
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = "PLA - Overture - White"
; filament_soluble = 0
; filament_spool_weight = 0
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = Generic
; fill_angle = 45
; fill_density = 15%
; fill_pattern = grid
; first_layer_acceleration = 0
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 60
; first_layer_extrusion_width = 0.42
; first_layer_height = 0.2
; first_layer_speed = 20
; first_layer_speed_over_raft = 30
; first_layer_temperature = 225
; full_fan_speed_layer = 0
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_enabled = 1
; gap_fill_speed = 30
; gcode_comments = 0
; gcode_flavor = marlin
; gcode_label_objects = 1
; gcode_resolution = 0.0125
; gcode_substitutions = 
; high_current_on_filament_swap = 0
; host_type = prusalink
; infill_acceleration = 0
; infill_anchor = 600%
; infill_anchor_max = 50
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.44
; infill_first = 0
; infill_overlap = 23%
; infill_speed = 60
; inherits_cummulative = ;"Generic PLA @CREALITY";"Creality Ender-3 Max (0.4 mm nozzle)"
; interface_shells = 0
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = ;AFTER_LAYER_CHANGE\n;{layer_z}
; layer_height = 0.2
; machine_limits_usage = emit_to_gcode
; machine_max_acceleration_e = 5000
; machine_max_acceleration_extruding = 500
; machine_max_acceleration_retracting = 1000
; machine_max_acceleration_travel = 500
; machine_max_acceleration_x = 500
; machine_max_acceleration_y = 500
; machine_max_acceleration_z = 100
; machine_max_feedrate_e = 60
; machine_max_feedrate_x = 500
; machine_max_feedrate_y = 500
; machine_max_feedrate_z = 10
; machine_max_jerk_e = 5
; machine_max_jerk_x = 8
; machine_max_jerk_y = 8
; machine_max_jerk_z = 0.4
; machine_min_extruding_rate = 0
; machine_min_travel_rate = 0
; max_fan_speed = 100
; max_layer_height = 0.32
; max_print_height = 340
; max_print_speed = 100
; max_volumetric_extrusion_rate_slope_negative = 0
; max_volumetric_extrusion_rate_slope_positive = 0
; max_volumetric_speed = 0
; min_bead_width = 85%
; min_fan_speed = 100
; min_feature_size = 25%
; min_layer_height = 0.06
; min_print_speed = 15
; min_skirt_length = 4
; mmu_segmented_region_interlocking_depth = 0
; mmu_segmented_region_max_width = 0
; notes = 
; nozzle_diameter = 0.4
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = {input_filename_base}_{print_time}_{digits(layer_height,1,2)}mm_{temperature[0]}C_{filament_type[0]}_{printer_model}.gcode
; overhang_fan_speed_0 = 0
; overhang_fan_speed_1 = 0
; overhang_fan_speed_2 = 0
; overhang_fan_speed_3 = 0
; overhang_speed_0 = 15
; overhang_speed_1 = 15
; overhang_speed_2 = 20
; overhang_speed_3 = 25
; overhangs = 0
; parking_pos_retraction = 92
; pause_print_gcode = M25 ; pause print
; perimeter_acceleration = 0
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.44
; perimeter_generator = arachne
; perimeter_speed = 60
; perimeters = 3
; physical_printer_settings_id = 
; post_process = 
; print_settings_id = 0.20 mm NORMAL SPEED (0.4 mm nozzle) @CREALITY
; printer_model = ENDER3MAX
; printer_notes = Don't remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_CREALITY\nPRINTER_MODEL_ENDER3MAX\nPRINTER_HAS_BOWDEN
; printer_settings_id = My Creality Ender-3 Max (0.4 mm nozzle)
; printer_technology = FFF
; printer_variant = 0.4
; printer_vendor = 
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 0
; resolution = 0
; retract_before_travel = 2
; retract_before_wipe = 70%
; retract_layer_change = 1
; retract_length = 3
; retract_length_toolchange = 1
; retract_lift = 0
; retract_lift_above = 0.2
; retract_lift_below = 0
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 60
; seam_position = nearest
; silent_mode = 0
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 0
; skirt_distance = 3
; skirt_height = 2
; skirts = 1
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 20
; small_perimeter_speed = 30
; solid_infill_acceleration = 0
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.44
; solid_infill_speed = 60
; spiral_vase = 0
; staggered_inner_seams = 0
; standby_temperature_delta = -5
; start_filament_gcode = "; Filament gcode\n"
; start_gcode = G90 ; use absolute coordinates\nM83 ; extruder relative mode\nM104 S150 ; set temporary nozzle temp to prevent oozing during homing\nM140 S{first_layer_bed_temperature[0]} ; set final bed temp\nG4 S30 ; allow partial nozzle warmup\nG28 ; home all axis\nG1 Z50 F240\nG1 X2.0 Y10 F3000\nM104 S{first_layer_temperature[0]} ; set final nozzle temp\nM190 S{first_layer_bed_temperature[0]} ; wait for bed temp to stabilize\nM109 S{first_layer_temperature[0]} ; wait for nozzle temp to stabilize\nG1 Z0.28 F240\nG92 E0\nG1 X2.0 Y140 E10 F1500 ; prime the nozzle\nG1 X2.3 Y140 F5000\nG92 E0\nG1 X2.3 Y10 E10 F1200 ; prime the nozzle\nG92 E0
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = -1
; support_material_buildplate_only = 0
; support_material_closing_radius = 2
; support_material_contact_distance = 0.15
; support_material_enforce_layers = 0
; support_material_extruder = 0
; support_material_extrusion_width = 0.36
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 0
; support_material_interface_layers = 2
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0.2
; support_material_interface_speed = 100%
; support_material_pattern = rectilinear
; support_material_spacing = 1
; support_material_speed = 40
; support_material_style = grid
; support_material_synchronize_layers = 0
; support_material_threshold = 40
; support_material_with_sheath = 0
; support_material_xy_spacing = 60%
; support_tree_angle = 40
; support_tree_angle_slow = 25
; support_tree_branch_diameter = 2
; support_tree_branch_diameter_angle = 5
; support_tree_branch_diameter_double_wall = 3
; support_tree_branch_distance = 1
; support_tree_tip_diameter = 0.8
; support_tree_top_rate = 15%
; temperature = 220
; template_custom_gcode = 
; thick_bridges = 1
; thin_walls = 0
; threads = 6
; thumbnails = 
; thumbnails_format = PNG
; toolchange_gcode = 
; top_fill_pattern = monotonic
; top_infill_extrusion_width = 0.4
; top_solid_infill_acceleration = 0
; top_solid_infill_speed = 30
; top_solid_layers = 5
; top_solid_min_thickness = 0
; travel_acceleration = 0
; travel_speed = 150
; travel_speed_z = 0
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wall_distribution_count = 1
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 1
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 0
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_cone_angle = 0
; wipe_tower_extra_spacing = 100%
; wipe_tower_extruder = 0
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 170
; wipe_tower_y = 140
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
; prusaslicer_config = end
